excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://LemonNewKid.github.io
title: badthoughts
tagline: suck me; i'm sour!
description: shitlord. man lover. recently deprogrammed.<br /><br />possibly a gay conservative.
paginate: 5